### ISSUE TITLE
follow more of a standard for help

### ISSUE THREAD

**Issue by larrymcd** [rough007/CyLR#23]
like most command line programs /? gets you a help listing vs -h . maybe make it validate what is passed as options and if something isn't right show help?

**Comment by Lansatac** [comment]
Supporting either windows style arguments or Linux style ones should be trivial, would you like to creates pull request with those changes? There is some limited failure help, is there a particular case that is missing?

**Comment by larrymcd** [comment]
My initial run I wanted to see the help and did "cylr /?" Which just ran the program and did a collection. I know it should be simple to add to the code for the help. Just wanted to rough up my buddy Alan to try and give him some more work to do, after dan raved about the program figured I would at least look it over. It looks nice from the quick test runs.

Larry

**Comment by rough007** [comment]
Issue is fixed in Master Branch
