### ISSUE TITLE
Change default paths List to use environment variables rather than hard coded drive letter

### ISSUE THREAD

**Issue by jj1985** [rough007/CyLR#32]

**Comment by Lansatac** [comment]
Split this into two issues, one for the default path being incorrect, and one for the feature request.

**Comment by Lansatac** [comment]
The -c option seems to cover this case pretty nicely. The defaults are there for convenience, and I'm not sure I'm hesitant to make this much more complicated when there's already a nice way to do this already.

**Comment by jj1985** [comment]
This is fair.  I'm just being nitpicky.  We can close this.
