### ISSUE TITLE
Trying to compile CyLR project in VS2015

### ISSUE THREAD

**Issue by tmitchell5280** [rough007/CyLR#55]
Hello,

I'd like to compile the CyLR project.  But I'm getting these errors. I did find this Library **ICSharpCode.SharpZipLib.dll** with project folders, did not seem to help me.

Here are the errors that I'm receiving.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'C:\VS2015\CyLR\CyLR-master\CyLR\bin\Debug\CyLR.exe' could not be found
CyLRTests	G:\Open_Source_DFIR-\CyLR\CyLR-master\CyLRTests\CSC	1	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'ZipArchive' could not be found (are you missing a using directive or an assembly reference?)
CyLR	C:\VS2015\CyLR\CyLR-master\CyLR\src\archive\NativeArchive.cs	10	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'ZipArchive' could not be found (are you missing a using directive or an assembly reference?)
CyLR	C:\VS2015\CyLR\CyLR-master\CyLR\src\archive\NativeArchive.cs	14	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'ZipArchiveMode' does not exist in the current context	CyLR
C:\VS2015\CyLR\CyLR-master\CyLR\src\archive\NativeArchive.cs	14	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'CompressionLevel' does not exist in the current context	CyLR
C:\VS2015\CyLR\CyLR-master\CyLR\src\archive\NativeArchive.cs	19	Active

I'm hoping that all that I'm currently missing is the **ZipArchive** Reference File.

Thanks for any and all help,

Take Care,

-Troy

**Comment by Lansatac** [comment]
Hi Troy, thanks for taking the time to file an issue. Are you trying to build with Visual Studio or Xamarin?
Can you see which options are available in the build configuration dropdown? There should be Debug and Release and the next dropdown over should be which framework you're currently targeting. Does changing that configuration to Framework 4.0 allow you to build?

**Comment by tmitchell5280** [comment]
Hi Lansatac,

Yep, that did the trick. Switching to .NET FW 4.0, let me successfully build the project.

Thanks again for the help.

Take Care,

-Troy

**Comment by Lansatac** [comment]
Thanks for verifying that. We deprecated the 4.5 builds a while ago, but I still need to clean up the build settings.
