### ISSUE TITLE
Update documentation for Linux & MacOS

### ISSUE THREAD

**Issue by ThetaGamma** [rough007/CyLR#61]
As CDQR works with almost any OS, it would be helpful to have a "cross-plattform" CyLR or at least a Non-Windows-CyLR. 
Basically it could be a script that collects the files for which parsers in [Parser Tracebility Matrix] (https://github.com/rough007/CDQR/blob/master/docs/Parser%20Traceability%20Matrix.xlsx) are defined

**Comment by Lansatac** [comment]
CyLR is supported on Linux and OSX via Mono (http://www.mono-project.com).
To use it, simply run it like this:
`mono CyLR.exe <options>`
 We are trying to use the mkbundle utility to create a standalone executable for posix systems, but we've been struggling to make it work.

**Comment by rough007** [comment]
Please check out the latest release notes to see what it collects on MacOS and Linux machines right now

**Comment by Lansatac** [comment]
It is perhaps also worth noting that you can always collect custom artifact lists by either piping in a list of artifacts or by using the '-c' option.

**Comment by ThetaGamma** [comment]
I suggest updating the README according to these Tipps -> Pull request  #done #62

**Comment by Lansatac** [comment]
Yeah, our documentation has gotten a little out of date and we really should be calling that out. Thanks for the PR!

**Comment by Lansatac** [comment]
Fixed in #62
